/**
 * SYSTÈME D'AUTONOMIE INTELLIGENTE - YAMTIKEN BEHEMOTH
 * Automatisations, CRON jobs, et IA prédictive
 */

import prisma from '../lib/prisma.js'
import { sendEmail } from '../lib/email.js'
import { generateRelancePDF } from '../lib/pdf.js'

// ============================================
// AUTOMATISATIONS RECOUVREMENT
// ============================================

/**
 * Génère automatiquement les relances pour les loyers en retard
 * Exécution: Tous les jours à 9h00
 */
export const autoGenerateRelances = async () => {
  console.log('🤖 [AUTO] Génération automatique des relances...')
  
  try {
    // Trouver les baux avec loyers en retard
    const bauxEnRetard = await prisma.lease.findMany({
      where: {
        statut: 'ACTIF',
        payments: {
          none: {
            datePaiement: {
              gte: new Date(new Date().setDate(1)) // Depuis début mois
            }
          }
        }
      },
      include: {
        client: true,
        unite: { include: { building: true } }
      }
    })
    
    let created = 0
    
    for (const bail of bauxEnRetard) {
      // Vérifier si une relance existe déjà pour ce mois
      const existingRelance = await prisma.relance.findFirst({
        where: {
          bailId: bail.id,
          dateRelance: {
            gte: new Date(new Date().setDate(1))
          }
        }
      })
      
      if (!existingRelance) {
        // Créer la relance automatique
        await prisma.relance.create({
          data: {
            bailId: bail.id,
            clientId: bail.clientId,
            type: 'LOYER',
            montantDu: bail.loyerMensuel,
            dateRelance: new Date(),
            statut: 'EN_ATTENTE',
            priorite: calculatePriority(bail),
            messageAuto: generateRelanceMessage(bail),
            autoGenerated: true
          }
        })
        created++
      }
    }
    
    console.log(`✅ [AUTO] ${created} relances générées`)
    return { success: true, count: created }
  } catch (error) {
    console.error('❌ [AUTO] Erreur génération relances:', error)
    return { success: false, error: error.message }
  }
}

/**
 * Envoie automatiquement les relances par email/SMS
 * Exécution: Tous les jours à 10h00
 */
export const autoSendRelances = async () => {
  console.log('🤖 [AUTO] Envoi automatique des relances...')
  
  try {
    const relances = await prisma.relance.findMany({
      where: {
        statut: 'EN_ATTENTE',
        autoGenerated: true,
        dateEnvoi: null
      },
      include: {
        client: true,
        bail: { include: { unite: { include: { building: true } } } }
      },
      take: 50 // Limiter à 50 par batch
    })
    
    let sent = 0
    
    for (const relance of relances) {
      try {
        // Envoyer email
        await sendEmail({
          to: relance.client.email,
          subject: `Relance loyer - ${relance.bail.unite.building.nom}`,
          template: 'relance',
          data: {
            client: relance.client,
            bail: relance.bail,
            montant: relance.montantDu,
            dateLimite: getDateLimite()
          }
        })
        
        // Marquer comme envoyé
        await prisma.relance.update({
          where: { id: relance.id },
          data: {
            dateEnvoi: new Date(),
            canal: 'EMAIL'
          }
        })
        
        sent++
      } catch (err) {
        console.error(`❌ [AUTO] Erreur envoi relance ${relance.id}:`, err)
      }
    }
    
    console.log(`✅ [AUTO] ${sent} relances envoyées`)
    return { success: true, count: sent }
  } catch (error) {
    console.error('❌ [AUTO] Erreur envoi relances:', error)
    return { success: false, error: error.message }
  }
}

// ============================================
// AUTOMATISATIONS ALERTES
// ============================================

/**
 * Détecte et crée les alertes automatiques
 * Exécution: Toutes les heures
 */
export const autoDetectAlerts = async () => {
  console.log('🤖 [AUTO] Détection alertes...')
  
  const alerts = []
  
  try {
    // 1. Alertes contrats expirant (moins de 30 jours)
    const contratsExpirant = await prisma.lease.findMany({
      where: {
        statut: 'ACTIF',
        dateFin: {
          lte: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
          gte: new Date()
        }
      },
      include: { client: true, unite: { include: { building: true } } }
    })
    
    for (const contrat of contratsExpirant) {
      const daysLeft = Math.ceil((contrat.dateFin - new Date()) / (1000 * 60 * 60 * 24))
      alerts.push({
        type: 'CONTRAT_EXPIRANT',
        severity: daysLeft <= 7 ? 'CRITIQUE' : daysLeft <= 15 ? 'HAUTE' : 'MOYENNE',
        message: `Contrat de ${contrat.client.nom} expire dans ${daysLeft} jours`,
        entityType: 'LEASE',
        entityId: contrat.id
      })
    }
    
    // 2. Alertes unités vacantes depuis plus de 30 jours
    const unitesVacantes = await prisma.unite.findMany({
      where: {
        statut: 'VACANT',
        updatedAt: {
          lte: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)
        }
      },
      include: { building: true }
    })
    
    for (const unite of unitesVacantes) {
      alerts.push({
        type: 'UNITE_VACANTE_LONGUE',
        severity: 'MOYENNE',
        message: `Unité ${unite.nom} vacante depuis plus de 30 jours`,
        entityType: 'UNITE',
        entityId: unite.id
      })
    }
    
    // 3. Alertes paiements en retard (plus de 10 jours)
    const paiementsRetard = await prisma.lease.findMany({
      where: {
        statut: 'ACTIF',
        dateDebut: {
          lte: new Date(new Date().setDate(1)) // Commencé avant ce mois
        }
      },
      include: {
        client: true,
        payments: {
          where: {
            datePaiement: {
              gte: new Date(new Date().setDate(1))
            }
          }
        }
      }
    })
    
    const bauxSansPaiement = paiementsRetard.filter(b => b.payments.length === 0)
    
    for (const bail of bauxSansPaiement) {
      alerts.push({
        type: 'LOYER_NON_PAYE',
        severity: 'HAUTE',
        message: `Loyer non payé pour ${bail.client.nom}`,
        entityType: 'LEASE',
        entityId: bail.id
      })
    }
    
    // Créer les alertes en base
    let created = 0
    for (const alert of alerts) {
      const existing = await prisma.alerte.findFirst({
        where: {
          type: alert.type,
          entityId: alert.entityId,
          statut: { not: 'RESOLUE' }
        }
      })
      
      if (!existing) {
        await prisma.alerte.create({
          data: {
            ...alert,
            statut: 'NOUVELLE',
            autoGenerated: true
          }
        })
        created++
      }
    }
    
    console.log(`✅ [AUTO] ${created} alertes créées`)
    return { success: true, count: created, alerts }
  } catch (error) {
    console.error('❌ [AUTO] Erreur détection alertes:', error)
    return { success: false, error: error.message }
  }
}

// ============================================
// AUTOMATISATIONS RAPPORTS
// ============================================

/**
 * Génère et envoie les rapports automatiques
 * Exécution: Hebdomadaire (Lundi 8h)
 */
export const autoGenerateReports = async () => {
  console.log('🤖 [AUTO] Génération rapports automatiques...')
  
  try {
    // Rapport hebdomadaire
    const rapport = await generateWeeklyReport()
    
    // Envoyer aux administrateurs
    const admins = await prisma.user.findMany({
      where: { role: { in: ['ADMIN', 'SUPER_ADMIN', 'DIRECTION'] } }
    })
    
    for (const admin of admins) {
      await sendEmail({
        to: admin.email,
        subject: 'Rapport hebdomadaire - YAMTIKEN BEHEMOTH',
        template: 'report',
        attachments: [{ filename: 'rapport.pdf', content: rapport.pdf }]
      })
    }
    
    console.log(`✅ [AUTO] Rapport envoyé à ${admins.length} administrateurs`)
    return { success: true }
  } catch (error) {
    console.error('❌ [AUTO] Erreur génération rapport:', error)
    return { success: false, error: error.message }
  }
}

// ============================================
// IA PRÉDICTIVE - RECOMMANDATIONS
// ============================================

/**
 * Analyse les données et génère des recommandations
 * Exécution: Quotidienne
 */
export const generateAIRecommendations = async () => {
  console.log('🧠 [IA] Génération recommandations intelligentes...')
  
  try {
    const recommendations = []
    
    // 1. Recommandation: Augmenter loyer sur unités sous-evaluées
    const unitesSousEvaluees = await prisma.unite.findMany({
      where: {
        statut: 'OCCUPE',
        loyer: {
          lt: prisma.unite.aggregate({
            where: { buildingId: { equals: prisma.unite.fields.buildingId } },
            _avg: { loyer: true }
          })._avg.loyer * 0.8
        }
      },
      include: { building: true }
    })
    
    if (unitesSousEvaluees.length > 0) {
      recommendations.push({
        type: 'PRICING',
        priority: 'HAUTE',
        title: 'Unités sous-évaluées détectées',
        description: `${unitesSousEvaluees.length} unités ont un loyer inférieur à 80% de la moyenne de l'immeuble`,
        action: 'ReviewPricing',
        potentialGain: calculatePotentialGain(unitesSousEvaluees),
        entities: unitesSousEvaluees.map(u => ({ id: u.id, type: 'UNITE' }))
      })
    }
    
    // 2. Recommandation: Relance proactive clients à risque
    const clientsRisque = await prisma.client.findMany({
      where: {
        leases: {
          some: {
            statut: 'ACTIF',
            payments: {
              none: {
                datePaiement: {
                  gte: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000)
                }
              }
            }
          }
        }
      }
    })
    
    if (clientsRisque.length > 0) {
      recommendations.push({
        type: 'RECOUVREMENT',
        priority: 'CRITIQUE',
        title: 'Clients à risque détectés',
        description: `${clientsRisque.length} clients n'ont pas payé depuis 45+ jours`,
        action: 'ImmediateRecovery',
        entities: clientsRisque.map(c => ({ id: c.id, type: 'CLIENT' }))
      })
    }
    
    // 3. Recommandation: Optimisation occupation
    const statsOccupation = await getOccupationStats()
    if (statsOccupation.taux < 85) {
      recommendations.push({
        type: 'MARKETING',
        priority: 'MOYENNE',
        title: 'Taux d\'occupation faible',
        description: `Taux actuel: ${statsOccupation.taux}%. Objectif: 90%`,
        action: 'LaunchMarketingCampaign',
        potentialGain: statsOccupation.potentielManque * 12 // Annuel
      })
    }
    
    // Sauvegarder les recommandations
    for (const rec of recommendations) {
      await prisma.recommendation.upsert({
        where: {
          id: `${rec.type}_${new Date().toISOString().slice(0, 10)}`
        },
        update: rec,
        create: {
          id: `${rec.type}_${new Date().toISOString().slice(0, 10)}`,
          ...rec,
          dateCreated: new Date(),
          status: 'PENDING'
        }
      })
    }
    
    console.log(`🧠 [IA] ${recommendations.length} recommandations générées`)
    return { success: true, recommendations }
  } catch (error) {
    console.error('❌ [IA] Erreur génération recommandations:', error)
    return { success: false, error: error.message }
  }
}

// ============================================
// HELPERS
// ============================================

const calculatePriority = (bail) => {
  const joursRetard = new Date().getDate() - 5 // Assume échéance le 5
  if (joursRetard > 20) return 'CRITIQUE'
  if (joursRetard > 10) return 'HAUTE'
  return 'MOYENNE'
}

const generateRelanceMessage = (bail) => {
  return `Cher ${bail.client.prenom},\n\n` +
    `Nous constatons que votre loyer pour l'unité ${bail.unite.nom} ` +
    `n'a pas été réglé pour ce mois.\n\n` +
    `Montant dû: ${bail.loyerMensuel.toLocaleString()} FCFA\n` +
    `Merci de régulariser votre situation dans les plus brefs délais.`
}

const getDateLimite = () => {
  const date = new Date()
  date.setDate(date.getDate() + 7)
  return date.toLocaleDateString('fr-FR')
}

const generateWeeklyReport = async () => {
  // Implémentation simplifiée
  return { pdf: Buffer.from('PDF content'), data: {} }
}

const calculatePotentialGain = (unites) => {
  return unites.reduce((sum, u) => sum + (u.loyer * 0.2), 0) // 20% augmentation
}

const getOccupationStats = async () => {
  const total = await prisma.unite.count()
  const occupees = await prisma.unite.count({ where: { statut: 'OCCUPE' } })
  const vacantes = total - occupees
  
  const loyerMoyen = await prisma.unite.aggregate({
    where: { statut: 'OCCUPE' },
    _avg: { loyer: true }
  })
  
  return {
    taux: Math.round((occupees / total) * 100),
    potentielManque: vacantes * (loyerMoyen._avg.loyer || 0)
  }
}

// ============================================
// CRON SCHEDULE CONFIGURATION
// ============================================

export const CRON_JOBS = {
  // Quotidien 9h00
  '0 9 * * *': autoGenerateRelances,
  
  // Quotidien 10h00
  '0 10 * * *': autoSendRelances,
  
  // Toutes les heures
  '0 * * * *': autoDetectAlerts,
  
  // Hebdomadaire Lundi 8h00
  '0 8 * * 1': autoGenerateReports,
  
  // Quotidien 6h00 (IA)
  '0 6 * * *': generateAIRecommendations
}

export default {
  autoGenerateRelances,
  autoSendRelances,
  autoDetectAlerts,
  autoGenerateReports,
  generateAIRecommendations,
  CRON_JOBS
}
