-- Créer tous les types ENUM nécessaires pour Prisma
CREATE TYPE "Role" AS ENUM ('SUPER_ADMIN', 'ADMIN', 'SECRETAIRE', 'AGENT_RECOUVREMENT', 'DIRECTION');
CREATE TYPE "TypeClient" AS ENUM ('SOUSCRIPTEUR', 'CLIENT');
CREATE TYPE "TypeBuilding" AS ENUM ('R2', 'R3', 'R4', 'VILLA', 'COUR_COMMUNE');
CREATE TYPE "TypeUnite" AS ENUM ('STUDIO', 'CHAMBRE', 'CHAMBRE_SALON', 'MAGASIN');
CREATE TYPE "StatutUnite" AS ENUM ('VACANT', 'OCCUPE', 'RESERVE');
CREATE TYPE "StatutLease" AS ENUM ('ACTIF', 'TERMINE', 'RESILIE');
CREATE TYPE "ModePaiement" AS ENUM ('ESPECES', 'VIREMENT', 'MOBILE_MONEY', 'CHEQUE');
CREATE TYPE "TypeBien" AS ENUM ('APPARTEMENT', 'MAISON', 'VILLA', 'STUDIO', 'BUREAU', 'COMMERCE', 'ENTREPOT', 'TERRAIN');
CREATE TYPE "StatutBien" AS ENUM ('DISPONIBLE', 'LOUE', 'VENDU', 'EN_RENOVATION', 'RESERVE');
CREATE TYPE "TypeContrat" AS ENUM ('LOCATION', 'VENTE');
CREATE TYPE "StatutContrat" AS ENUM ('ACTIF', 'RESILIE', 'TERMINE', 'EN_COURS');
CREATE TYPE "StatutPaiement" AS ENUM ('PAYE', 'EN_RETARD', 'PARTIEL', 'EN_ATTENTE');
CREATE TYPE "MotifVisite" AS ENUM ('DECOUVERTE', 'NEGOCIATION', 'RECLAMATION', 'AUTRE');
CREATE TYPE "StatutRelance" AS ENUM ('EN_ATTENTE', 'EFFECTUEE', 'ANNULEE');
CREATE TYPE "TypeAlerte" AS ENUM ('PAIEMENT_ECHEANCE', 'BAIL_EXPIRATION', 'RELANCE_VISITE', 'GENERAL');
CREATE TYPE "TypeCommission" AS ENUM ('FIXE', 'POURCENTAGE');
CREATE TYPE "StatutCommission" AS ENUM ('EN_ATTENTE', 'PAYEE');
